<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chapter 8 | Eloquent JavaScript Sandbox</title>
    <link rel="stylesheet" href="../styles/normalize.css">
    <link rel="stylesheet" href="../styles/main.css">
</head>

<body>
    <header>
        <h1>WDD 330 Portfolio</h1>
        <h2>Jennifer C. Thomas</h2>
    </header>

    <main>
        <h2>Eloquent JavaScript Sandbox Exercises</h2>
        <h3>Chapter 8</h3>
        <h4>Retry</h4>
        <p>Say you have a function <code>primitiveMultiply</code> that in 20 percent of cases multiplies two numbers 
            and in the other 80 percent of cases raises an exception of type <code>MultiplicatorUnitFailure</code>. 
            Write a function that wraps this clunky function and just keeps trying until a call succeeds, 
            after which it returns the result.</p>
        <pre><code>
            class MultiplicatorUnitFailure extends Error {}

            function primitiveMultiply(a, b) {
              if (Math.random() < 0.2) {
                return a * b;
              } else {
                throw new MultiplicatorUnitFailure("Klunk");
              }
            }
            
            function reliableMultiply(a, b) {
              for (;;) {
                try {
                  return primitiveMultiply(a, b);
                } catch (e) {
                  if (!(e instanceof MultiplicatorUnitFailure))
                    throw e;
                }
              }
            }
            
            console.log(reliableMultiply(8, 8));
            // → 64
        </code></pre>

        <h4>The Locked Box</h4>
        <p>Consider the following (rather contrived) object:</p>
        <pre><code>
            const box = {
                locked: true,
                unlock() { this.locked = false; },
                lock() { this.locked = true;  },
                _content: [],
                get content() {
                  if (this.locked) throw new Error("Locked!");
                  return this._content;
                }
              };
        </code></pre>
        <p>Write a function called <code>withBoxUnlocked</code> that takes a function value as argument, unlocks the box, 
            runs the function, and then ensures that the box is locked again before returning, 
            regardless of whether the argument function returned normally or threw an exception.</p>
        <pre><code>              
              function withBoxUnlocked(body) {
                // Your code here.
              }
              
              withBoxUnlocked(function() {
                box.content.push("gold piece");
              });
              
              try {
                withBoxUnlocked(function() {
                  throw new Error("Pirates on the horizon! Abort!");
                });
              } catch (e) {
                console.log("Error raised: " + e);
              }
              console.log(box.locked);
              // → true
        </code></pre>
    </main>
    <div class="buttonHolder">
        <form>
            <input type="button" id="backBtn" value="Return to previous page" onclick="history.back()">
        </form>
    </div>
    <footer>
        <p>&copy;2021 | Jennifer C. Thomas | Location: Utah | <a href="http://www.byui.edu/online"
                target="_blank">BYU-Idaho Online Learning</a></p>
        Last Updated: <span id="currentdate"></span>
    </footer>
    <script src="../js/currentdate.js"></script>
</body>

</html>